### PR TITLE
Add support for custom server

### PR DESCRIPTION
**Pull request by apteryxxyz**
I've just published an experimental version of Next WS (`next-ws@experimental`) that adds support for custom servers. It appears to work but it's not fully tested.

The way it works is by you assigning your own http server (and optionally ws server) to a global variable, which Next WS will check for when setting up the server. I'm not a fan of assigning to global, but I prefer this over having to patch more things in Next.js.

`CustomHttpServer`, `CustomWsServer` are two ~~symbols~~ strings that get exported from `next-ws/server` and can be used to assign your custom http server to the global object.

This is the setup I used that works:

```js
// server.js
const { Server } = require('http');
const { WebSocketServer } = require('ws');
const { parse } = require('url');
const next = require('next');
const { CustomHttpServer, CustomWsServer } = require('next-ws/server');

const dev = process.env.NODE_ENV !== 'production';
const hostname = 'localhost';
const port = 3000;

const httpServer = new Server();
global[CustomHttpServer] = httpServer;
const wsServer = new WebSocketServer({ noServer: true });
global[CustomWsServer] = wsServer;

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  httpServer
    .on('request', async (req, res) => {
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    })
    .listen(port, () => {
      console.log(` ▲ Ready on http://${hostname}:${port}`);
    });
});
```

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
@apteryxxyz not sure if related, but when running another - totally unrelated project, based on next.js 14 but not using next-ws (or a custom server) I am getting this error

> Error: Cannot find module 'next-ws/server'

I can't remember seeing this before, hence why I add this as a comment in this PR, even though it might be unrelated (in which case, I can create a new issue instead)

**Comment by apteryxxyz** [comment]
In that case I think Next WS patches the cached/linked version of the package. Not too sure of a way to resolve this, other than just maybe adding a try catch to where Next WS is required.

**Comment by chinna2580** [comment]
Will this merged to main branch soon?

**Comment by sanyam810** [comment]
Is there a way to include SSL options such as adding an SSL certificate and key, during WebSocket server initialization? Doesn't necessary need to be a custom server. I have opened a issue for it, would really appreciate if you share some leads on it.

**Comment by apteryxxyz** [comment]
This branch is being closed in favour of [major-improvements](https://github.com/apteryxxyz/next-ws/tree/major-improvements).

**Pull request closed without merging**
